bookers2-advanced-issue/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'home/about' => 'homes#about'
end

bookers2-advanced-issue/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2-advanced-issue/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

bookers2-advanced-issue/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2-advanced-issue/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2-advanced-issue/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

bookers2-advanced-issue/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

bookers2-advanced-issue/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

bookers2-advanced-issue/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @post_comment = PostComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
     unless @book.user == current_user
       redirect_to books_path
     end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2-advanced-issue/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

bookers2-advanced-issue/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

bookers2-advanced-issue/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = book.id
    if comment.save
      redirect_to book_path(book)
    else
      redirect_to request.referer
    end
  end

  def destroy
    PostComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

bookers2-advanced-issue/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

bookers2-advanced-issue/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

bookers2-advanced-issue/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2-advanced-issue/app/helpers/books_helper.rb
module BooksHelper
end

bookers2-advanced-issue/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2-advanced-issue/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2-advanced-issue/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2-advanced-issue/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2-advanced-issue/app/helpers/users_helper.rb
module UsersHelper
end

bookers2-advanced-issue/app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete do %>
        ♥<%= book.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post do %>
        ♡<%= book.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

bookers2-advanced-issue/app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

bookers2-advanced-issue/app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= render 'books/favorite', book: book %></td>
        <td><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-advanced-issue/app/views/books/_post_comment.html.erb
<table class="comments" 'container'>
  <% book.post_comments.each do |post_comment| %>
    <tr class='row'>
      <td class='col-md-5'>
        <%= attachment_image_tag post_comment.user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg" %><br>
        <%= post_comment.user.name %>
      </td>
      <td class='col-md-5'>
        <%= post_comment.comment %>
      </td>
      <td class='col-md-2'>
        <% if post_comment.user == current_user %>
          <%= link_to 'Destroy', book_post_comment_path(book, post_comment), method: :delete, class: "btn btn-sm btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<table class="new-comment">
  <%= form_with(model:[book, post_comment], local: true) do |f| %>
    <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %><br>
    <%= f.submit "送信する" %>
  <% end %>
</table>

bookers2-advanced-issue/app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <%= render 'layouts/errors', obj: @book %>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

bookers2-advanced-issue/app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <%= render 'layouts/errors', obj: @book %>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

bookers2-advanced-issue/app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, size: "100x100", fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td><%= render 'books/favorite', book: @book %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <td>コメント件数：<%= @book.post_comments.count %></td>
          <% end %>
        </tr>
      </table>
      <table class='table'><%= render 'books/post_comment', book: @book, post_comment: @post_comment %></table>
    </div>
  </div>
</div>

bookers2-advanced-issue/app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

bookers2-advanced-issue/app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

bookers2-advanced-issue/app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

bookers2-advanced-issue/app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

bookers2-advanced-issue/app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' Users',users_path,class: 'fas fa-users nav-link text-light' %></li>
          <li><%= link_to ' Books',books_path ,class: 'fas fa-book-open nav-link text-light'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' About',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

bookers2-advanced-issue/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

bookers2-advanced-issue/app/views/relationships/followers.html.erb
<table class='table'>
<h2>Follower Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

bookers2-advanced-issue/app/views/relationships/followings.html.erb
<table class='table'>
<h2>Follow Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

bookers2-advanced-issue/app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, size: "50x50", fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>
          <% if user != current_user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-advanced-issue/app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, size: "100x100", fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

bookers2-advanced-issue/app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

bookers2-advanced-issue/app/views/users/index.html.erb
<div class='container'>
<div class='row'>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='col-md-3'>
    <h2>User info</h2>
    <%= render 'info', user: current_user %>
    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>
  </div>
  <div class='col-md-8 offset-md-1'>
    <h2>Users</h2>
    <%= render 'index',users: @users %>
  </div>
</div>
</div>

bookers2-advanced-issue/app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <% if @user != current_user %>
        <% if current_user.following?(@user) %>
          <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
        <% end %>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>